name: Build Docker Image
on:
  push:
    branches:
      - master
    paths:
      - "VERSION.txt"

jobs:
  docker-build:
    name: Build Image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - continue-on-error: false
        name: Build Docker Image
        run: |
          TAG=$(cat VERSION.txt)
          echo $TAG
          HELM_VERSION=$(cat HELM_VERSION.txt)
          docker build --build-arg VERSION=$HELM_VERSION -t nanda/helm-template-validator:$TAG .

      - name: Log in to dockerhub registry
        run: docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push to Docker Hub
        run: |
          TAG=$(cat VERSION.txt)
          echo $TAG
          docker push nanda/helm-template-validator:$TAG
